### ISSUE TITLE
blocking user input

### ISSUE THREAD

**Issue by lemonhead94** [Sweebi/tvProgress#1]
Since this is blocking the user while loading, how would you prepose to do this for a search bar?

Because you might just want to cancel a call, when the user puts in a new letter...
I think the idea is good but blocking the user completely isn't the best approach. 
So why not make an option for a less intrusive loading indicator?

**Comment by CedricEugeni** [comment]
Hi @lemonhead94,
Thanks for paying attention to our project.
We think that the case your are talking about and the use case we thought about for tvProgress are two distinct use case.

Indeed, tvProgress is intended to be used the same way SVProgressHUD should be use. It should be used to display loading of content.

Concerning the use case you are presenting, I would use a UISearchController like I would on iOS. The UISearchController is available in tvOS but not visible in the Interface Builder. Please refer to [this Apple documentation page](https://developer.apple.com/library/tvos/samplecode/UICatalogFortvOS/Introduction/Intro.html) to see how Apple indicates us to do.

I close this issue but if you think about use cases where tvProgress' way of handling inputs while loading may be problematic, feel free to open another one and we will gladly answer and maybe consider an option to make tvProgress less intrusive concerning user inputs.

**Comment by lemonhead94** [comment]
okay I'll open a new one with "tvProgress less intrusive option for user inputs"
