### ISSUE TITLE
tvProgress less intrusive option for user inputs

### ISSUE THREAD

**Issue by lemonhead94** [Sweebi/tvProgress#2]
One Use Case would be, when presenting a Loading Indicator, while the user starts typing in the UISearchController

**Comment by ghost** [comment]
Hi @lemonhead94,
Thanks to open this issues for reporting your user case.

When we started to develop this project, we didn't really think about create a loading indicator framework for your user cases.
We wanted creating a loader indicator view like SVProgressHUD, but with the tvOS design (a blur view in background).
We are actually thinking about other user case, but this is not really a priority for us today.

I close this issue, but don't hesitate to open others issues if you have any other questions.

Regards,

**Comment by CedricEugeni** [comment]
Hi @lemonhead94,

I'd like to add something about what @legomanfish just said.
When you have a keyboard and autocomplete just like in the use case your are talking about, you can call tvProgress to load before presenting autocomplete list.

The thing is that when you will present tvProgress, the whole screen will present tvProgress, your keyboard won't be visible anymore so you won't be able to add text anymore. That's one of the reason why we think that this use case isn't relevant for using tvProgress, the same way it would be irrelevant to use SVProgressHUD for this use case on iOS.

**Comment by lemonhead94** [comment]
sorry but that's just not true...

I'm using a custom version of SVProgressHUD in my project right now, and it never blocks the user from typing on the keyboard. And as far as I can remember that's also the use case on ios devices...

**Comment by CedricEugeni** [comment]
As we can see in [SVProgressHUD's README](https://github.com/SVProgressHUD/SVProgressHUD) : 

> Use SVProgressHUD wisely! Only use it if you absolutely need to perform a task before taking the user forward. Bad use case examples: pull to refresh, infinite scrolling, sending message.

In my opinion, Autocomplete is typically a bad use case for SVProgressHUD.
But I can admit that we could use SVProgressHUD to do that if we want to.

Things are a bit different on tvOS. Indeed, textfield is filled with a virtual keyboard that you can only see on a specific view. That's the reason why Apple advises us to use a UISearchController. Doing so, the indicator view should be integrated into the UISearchController view (maybe in the result view).

In addition tvProgress' design is to be guidelines compliant and respectful. And that comes with the use of a UIBlurView in full screen (for the moment at least).

The thing is that we are trying to make the difference here between what is a task and what is not. A task is a loading that you absolutely need to do (to use SVProgressHUD Readme's words). For the moment, we consider that the use case you describe about autocomplete is not a use case concerning a task but a use case concerning the display of some results (in other words, the view can live without the results of autocomplete to let you type text.)

**Comment by lemonhead94** [comment]
okay, i understand where you're coming from...

**Comment by CedricEugeni** [comment]
I still think that right now, it would be a bad idea to use tvProgress for the use case you are experiencing.
But we came to think of a solution.

The solution would be to be able to tell tvProgress which view is 'loading'. With this enhancement, we will be able tvProgress over the loading view instead of being displayed over the whole window.
That means we won't have to block user inputs anymore.

Does this solution suits you @lemonhead94 ?

**Comment by lemonhead94** [comment]
that does sound like a pretty good solution to me.
so the keyboard would be on top of the loading, 'tvProgess view' then?

**Comment by CedricEugeni** [comment]
Yes it would.
Maybe I'll make a screenshot to show what it could be like tomorrow.

**Comment by CedricEugeni** [comment]
1.1 release will be available in a few minutes and should provide the proposed implementation for your use case @lemonhead94 :)
